name: ServerPassword
main: hu.kazu.serverpassword.ServerPasswordPlugin
version: 1.0.0
api-version: '1.21'
author: Kazu
commands:
  login:
    description: Jelentkezz be a szerver-jelszóval.
    usage: /login <jelszó>
  serverpassword:
    description: Plugin beállítások (reload).
    usage: /serverpassword reload
    permission: serverpassword.admin
permissions:
  serverpassword.bypass:
    description: Nem kell jelszó (OP-oknak adható).
    default: op
  serverpassword.admin:
    description: Admin parancsok
    default: op
