name: Build ServerPassword

on:
  push:
    branches: [ "**" ]
    tags: [ "v*" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: serverpassword-jar
          path: build/libs/*.jar
          if-no-files-found: error

